#!/usr/bin/env bash
# Installs HAProxy version 1.8 with the following configurations:
#+    Enables management via the init script.
#+    Distributes requests using a round-robin algorithm.

sudo apt-get -y update
sudo apt-get -y install haproxy
sudo chown -R "$USER:$USER" /etc/haproxy/

printf %s "global
    log 127.0.0.1 local0 notice
    maxconn 2000
    user haproxy
    group haproxy

defaults
    log     global
    mode    http
    option  httplog
    option  dontlognull
    retries 3
    option redispatch
    timeout connect  5000
    timeout client  10000
    timeout server  10000

frontend http-in
    bind *:80
    mode http
    default_backend hbnb

backend hbnb
    stats enable
    stats uri /haproxy?stats
    balance roundrobin
    server 134489-web-01 54.87.238.34:80 check
    server 134489-web-02 100.25.30.179:80 check
" >> /etc/haproxy/haproxy.cfg
sudo service haproxy restart
